name: Build Docker Image

# Manually triggerable for first-time setup
on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  ACR_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}   # SP JSON :contentReference[oaicite:0]{index=0}

      - name: ACR Login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }} # azure/docker-login@v2 :contentReference[oaicite:1]{index=1}

      - name: Build Docker image
        run: |
          IMAGE_TAG=latest
          docker build -t $ACR_LOGIN_SERVER/ucc-info-chatbot:$IMAGE_TAG .

      - name: Push to ACR
        run: |
          IMAGE_TAG=latest
          docker push $ACR_LOGIN_SERVER/ucc-info-chatbot:$IMAGE_TAG
