name: Deploy & Update ACI

on:
  push:
    branches: [ main ]
concurrency:
  group: 'deploy-aci-${{ github.ref }}'
  cancel-in-progress: true
  
env:
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  ACR_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}

jobs:
  deploy-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build --no-cache -t $ACR_LOGIN_SERVER/ucc-info-chatbot:$IMAGE_TAG .
          docker push    $ACR_LOGIN_SERVER/ucc-info-chatbot:$IMAGE_TAG

      - name: Restart ACI to pull latest image
        run: |
          az container restart \
            --resource-group ucc-rag-info \
            --name ucc-info-chatbot-ci

